### ISSUE TITLE
pin-less seneca.client() should disable out of the box local services

### ISSUE THREAD

**Issue by nherment** [rjrodger/seneca-transport#19]
### ```client.js```

```
[...]
seneca.client({
  type: 'web',
  host: 'foobar.service.consul',
  port: 10001
});
```

### ```server.js```

```
[...]
seneca.use('postgresql-store')
seneca.listen({
  type: 'web',
  host: '0.0.0.0',
  port: 10001
});
```

When an entity is saved, ``client.js`` use mem-store instead of sending the queries to ``server.js``.

It'd be great to consider pin-less client declaration to be a send-all for everything that was not explicitely declared by the user and never rely on out of the box plugins when a seneca.client declaration match.

**Comment by nherment** [comment]
using ``seneca@0.6.1`` and ``seneca-transport@0.6.3``

**Comment by rjrodger** [comment]
the basic principle that local wins should be retained because this is simple to understand
also the principle that seneca is self-contained out of the box is important, so role:web,entity,transport are local by default

perhaps pin:* should provide this always remote behavior

**Comment by rjrodger** [comment]
ok, on reflection, the official solution is via options:
```js
seneca( { default_plugins:{"mem-store":false} } ) // etc.
```
