### ISSUE TITLE
Order of clients matter if using pins and the catchall handler

### ISSUE THREAD

**Issue by mcollina** [rjrodger/seneca-transport#21]
This might either be a bug or a documentation issue. The following code works:

```js
var s = require('seneca')()
          .client({ type: 'http', port: 8083 })
          .client({ type: 'tcp', port: 8081, pin: 'cmd:enqueue-remote,queue:q1' })
          .client({ type: 'tcp', port: 8082, pin: 'cmd:enqueue-remote,queue:q2' })
```

Being that everything is sent to the catch all handler, a part from what is pinned.

However, this does not:

```js
var s = require('seneca')()
          .client({ type: 'tcp', port: 8081, pin: 'cmd:enqueue-remote,queue:q1' })
          .client({ type: 'tcp', port: 8082, pin: 'cmd:enqueue-remote,queue:q2' })
          .client({ type: 'http', port: 8083 })
```

As everything will be handled by the catch all.

I suggest the catch all to throw an Error if something is already pinned, and in any case to update the documentation.

This issue is kind-of hard to debug, too. Basically you expect Seneca to route your messages accordingly, while it fails saying that `no matching action pattern found`.

(At least this is the behavior on Seneca 0.5).

**Comment by guyellis** [comment]
@nherment didn't we come across this in a project as well where something that we expected to be matched wasn't being matched?

**Comment by nherment** [comment]
I'm not sure but I think we had a similar situation with order vs pattern and we had to go through trial and error to find the right combination to make it work.

**Comment by rjrodger** [comment]
order does not matter anymore; most specific wins :)
