### ISSUE TITLE
Add some option in the listen method to allow the Access-Control-Allow-Origin: * header setting

### ISSUE THREAD

**Issue by xavidelgado** [rjrodger/seneca-transport#22]
I am consuming seneca services from a client in HTML, the browsers return an error due to the lack of Access-Control-Allow-Origin:* in the seneca returned header. It could be a good idea to have an option to  add this header using an option on the listen method.

**Comment by xavidelgado** [comment]
May be something like that could be interesting:

line 439: 
     var headers = {
          'Content-Type':   'application/json',
          'Cache-Control':  'private, max-age=0, no-cache, no-store',
          'Content-Length': buffer.Buffer.byteLength(outjson),
        }
        
        if (args.headers) {
          for (var header in args.headers) {
            headers[header] = args.headers[header];
          }
        }

**Comment by rjrodger** [comment]
The HTTP transport is not intended for external use. See https://github.com/rjrodger/seneca-web for creating external HTTP APIs
