### ISSUE TITLE
Set Timeout doesn't work

### ISSUE THREAD

**Issue by ambrumyan** [rjrodger/seneca-transport#23]
Even if timeout is set it takes default timeout ~ 33 seconds, I tried to set timeout from console as well same result. can anyone help?

var seneca = require('seneca')
seneca()
  .client({timeout:1000})

**Comment by iantocristian** [comment]
The global seneca timeout defaults to 33 seconds. You can do `seneca({timeout:1000})` to change that.

**Comment by ambrumyan** [comment]
Thanks

**Comment by danmo** [comment]
Is there anyway to set the timeout post instantiation ?

**Comment by danmo** [comment]
The following seems to do the job:

seneca.options({timeout: 999999999});
